export const COLUMNS_SET = "COLUMNS_SET";
export const COLUMNS_SET_DEFAULT = "COLUMNS_SET_DEFAULT";
export const COLUMN_TITLE_EDIT = "COLUMN_TITLE_EDIT";
export const COLUMN_TITLE_CHANGE = "COLUMN_TITLE_CHANGE";